name: info_popup
description: The simple way to show the user some information on your selected widget.
version: 4.3.2
maintainer: Salih Can Binboga
homepage: https://github.com/salihcanbinboga/info_popup
repository: https://github.com/salihcanbinboga/info_popup
issue_tracker: https://github.com/salihcanbinboga/info_popup/issues
screenshots:
  - description: "Info Popup Logo"
    path: assets/readme/package_profile.webp
topics:
  - popup
  - modal
  - dialog
  - alert
  - tooltip

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example:
    path: example
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
